title: Ember Octane Essentials
tagline: Build a real-world app with Ember's latest edition
description: Leave your Todo List apps a home
tags:
  - javascript
  - frameworks
  - frontend
  - ui
  - ember

template:
  name: ember-octane
  repo: ember-octane

before:
  - type: createIssue
    title: Getting Started with GitHub
    body: introduction.md
    action_id: introduction_issue