title: Ember Octane Essentials
tagline: Build a real-world app with Ember's latest edition
description:
  - Leave your Todo List apps a home
tags:
  - javascript
  - frameworks
  - frontend
  - ui
  - ember
